# Generated by Django 3.2 on 2023-09-25 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0003_rename_persist_dir_storagecontext_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storagecontext',
            old_name='index',
            new_name='persist_dir',
        ),
    ]
