# Generated by Django 3.2 on 2023-09-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0004_rename_index_storagecontext_persist_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagecontext',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
