# Generated by Django 3.2 on 2023-09-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0006_delete_storagecontext'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
    ]
