# Generated by Django 3.2 on 2023-09-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0009_auto_20230927_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='pdf_content',
            field=models.BinaryField(default=None, null=True),
        ),
    ]
