# Generated by Django 3.2 on 2023-09-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0010_alter_pdfdocument_pdf_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='pdf_content',
            field=models.BinaryField(default=b''),
        ),
    ]
