# Generated by Django 3.2 on 2023-09-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0013_auto_20230927_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfdocument',
            name='pdf_content',
        ),
        migrations.RemoveField(
            model_name='pdfdocument',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='pdf_file',
            field=models.FileField(null=True, upload_to='pdfs/'),
        ),
    ]
