# Generated by Django 3.2 on 2023-10-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0015_jsondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsondata',
            name='storage_directory',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
