# Generated by Django 3.2 on 2023-10-06 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0016_jsondata_storage_directory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsondata',
            name='name',
        ),
        migrations.RemoveField(
            model_name='jsondata',
            name='storage_directory',
        ),
    ]
