# Generated by Django 3.2 on 2023-10-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0017_auto_20231006_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsondata',
            name='json_data',
        ),
        migrations.AddField(
            model_name='jsondata',
            name='json_file',
            field=models.FileField(null=True, upload_to='jsons/'),
        ),
    ]
