# Generated by Django 3.2 on 2023-10-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0018_auto_20231006_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsondata',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
