# Generated by Django 3.2 on 2023-10-06 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0019_jsondata_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JSONData',
        ),
    ]
